Feature/domain models
ZenTaKr0fTeR111/MyPortfolio pull request #2
Opened 2024-07-07 21:43 UTC by DanilaKovaliou

сделал токько дата классы

2024-07-07 21:52 UTC, ZenTaKr0fTeR111 requested changes

2024-07-07 21:52 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/domain/models/Assets.kt
> +data class Assets(val name: String, val quantity: Int, val price: Double)
Этот класс абстрактным, добавить id и убрать количество.

2024-07-07 21:52 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/domain/models/Bonds.kt
> +data class Bonds(val name: String, val quantity: Int, val price: Double, val issuer: String, val maturityDate: String)
Этот и остальные наследуем от Asset

2024-07-07 21:53 UTC, DanilaKovaliou commented on app/src/main/java/com/example/myportfolio/domain/models/Bonds.kt
> +data class Bonds(val name: String, val quantity: Int, val price: Double, val issuer: String, val maturityDate: String)
как мне сказали наследования нет (для дата классов)

2024-07-07 22:13 UTC, ZenTaKr0fTeR111 commented
Куда теперь Asset пропал? Он должен быть абстрактным, от него наследуются другие активы

2024-07-07 22:16 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/domain/models/Bonds.kt
> +data class Bonds(val name: String, val quantity: Int, val price: Double, val issuer: String, val maturityDate: String)
Кто сказал? Паша? Кидай пулл реквест в чат тогда, пусть он разбирается

2024-07-07 23:04 UTC, ZenTaKr0fTeR111 requested changes
https://github.com/ZenTaKr0fTeR111/MyPortfolio/pull/2#issuecomment-2212593670

2024-07-08 05:57 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/myportfolio/domain/models/Bonds.kt
> +data class Bonds(val name: String, val quantity: Int, val price: Double, val issuer: String, val maturityDate: String)
Да, наследования нет от других дата классов. Но наследоваться от абстрактного класса можно, и в данном случае можно

2024-07-08 05:59 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/myportfolio/domain/models/Assets.kt
> +data class Assets(val name: String, val quantity: Int, val price: Double)
Количество вообще не относится к характеристикам ценной бумаги в общем, а относится к характеристикам ценной бумаги, находящейся в портфеле

2024-07-09 15:18 UTC, ZenTaKr0fTeR111 requested changes

2024-07-09 15:18 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/domain/models/Assets.kt
> +interface Asset
Это abstract class с общими для всех активов параметрами

2024-07-09 15:18 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/domain/models/Assets.kt
> +//data class Stock(val name: String, val quantity: Int, val price: Double, val symbol: String) : Asset
Это что такое?

2024-07-09 15:18 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/domain/models/Bonds.kt
> +    //val quantity: Int,
Это нормально удалить, не комментировать. И названия сущностей хотелось бы в единственном числе

2024-07-09 15:18 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/domain/models/Bonds.kt
> +    val currency:String,
Валюта тоже не нужна, мы же будем это в настройках менять

2024-07-09 15:18 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/domain/models/Currency.kt
> +    val secondName: String,
Что это за фамилия у валюты?

2024-07-09 15:18 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/domain/models/Stocks.kt
> +                  val Countryissuer: String,
Акции относятся к компаниям, а не странам

2024-07-09 15:18 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/sampledata/Assets_assets.kt
> +     val assets = listOf<Assets>()
А это зачем?

2024-07-09 15:18 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/sampledata/Repository.kt
> +}
Молодец что это уже сделал, но нужно рефакторить, а то глаза сломаются. Инденты нормальные проставь. И sampledata заверни в папку data.

2024-07-09 15:18 UTC, ZenTaKr0fTeR111 commented on app/build.gradle.kts
> +apply(from="../code_style/ktlint.gradle")
Это в идеале в отдельный комит нужно было вместе с рефакторингом, к доменным моделям оно не относится. Но ладно, так сойдет.

2024-07-09 15:18 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/API/RetrofitInstance.kt
> +object RetrofitInstance {
Зачем эти пустые объект и интерфейс?

2024-07-13 10:43 UTC, ZenTaKr0fTeR111 requested changes

2024-07-13 10:43 UTC, ZenTaKr0fTeR111 commented on app/build.gradle.kts
> +apply(from = "../code_style/ktlint.gradle")
Линтер явно не настроеный. Хук не стоит и папки не добавлены в проект.

2024-07-13 10:43 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/API/RetrofitInstance.kt
> +object RetrofitInstance {
?

2024-07-13 10:43 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/data/sampledata/Assets_assets.kt
> +// }
Удалять а не комментировать

2024-07-13 10:43 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/data/sampledata/Repository.kt
> +object Repository {
Это нужно как-то иначе назвать. Репозиторий у нас интерфейс в доменном слое, определяющий операции над данными. В data слое будут их реализации.

2024-07-13 10:43 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/domain/models/Stocks.kt
> +    val countryIssuer: String,
Акции не относятся к стране.

2024-07-29 22:02 UTC, closed without merging