Feature/asset list
ZenTaKr0fTeR111/MyPortfolio pull request #4
Opened 2024-07-15 00:46 UTC by ZenTaKr0fTeR111

2024-07-15 00:50 UTC, DanilaKovaliou approved these changes

2024-07-15 09:14 UTC, Valentin2508247 requested changes

2024-07-15 09:14 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/data/datasource/SampleData.kt
давай перенесем данные в класс AssetsSampleSource

2024-07-15 09:14 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/data/datasource/AssetsDataSource.kt
можно добавить больше методов для интерфейса AssetsDataSource
например, метод getBaseCurrency
+ добавить AssetsSampleSource тестовые данные внутрь класса

2024-07-15 09:14 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/domain/interactors/AssetInteractor.kt
> +    fun getAssets() = repository.getAssets()
обычно в Interactor или UseCase метод с логикой называют execute или invoke

2024-07-15 09:14 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/data/datasource/SampleData.kt
> +    Stock(3, "Visa Inc.", 26300, currencies.getValue(CurrencyCode.USD), "V"),
почему форматирование разное?

2024-07-15 09:14 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/domain/models/Asset.kt
> +    fun getPrice() = (price / 100.toDouble()).toString() + baseCurrency.symbol
непонятно из неймингов, зачем логика деления на 100
можно написать price / 100.0

2024-07-15 09:14 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/domain/models/Asset.kt
> +    fun getPrice() = (par / 100.toDouble()).toString() + baseCurrency.symbol
аналогично

2024-07-15 09:14 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/domain/models/Asset.kt
> +data class Currency(
опционально: можно реализовать Currency как sealed class

2024-07-15 09:14 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/AssetListViewModel.kt
> +    private fun getAssets() = interactor.getAssets()
лучше в getAssets получать данные и обновлять значение в LiveData

2024-07-15 09:14 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/AssetListViewModel.kt
> +        _assets.value = getAssets()
getAssets()

2024-07-15 09:14 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/DetailedAssetItemFragment.kt
> +        binding.assetDetails.text = "Asset #${args.assetId}"
через строковый ресурс с параметром

2024-07-15 09:14 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/rv/AssetViewHolder.kt
> +        with(asset as Stock) {
будет краш если придет не Asset
либо используйте поля и методы из Asset, либо сделайте отдельный ViewHolder для Stock

2024-07-15 09:14 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/rv/AssetViewHolder.kt
> +            binding.rateText.text = "$rate%"
лучше через строковые ресурсы

2024-07-15 09:14 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/rv/AssetViewHolder.kt
> +            binding.priceText.text = "1.00${baseCurrency.symbol}"
лучше через строковые ресурсы

2024-07-15 09:14 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/rv/AssetViewHolder.kt
> +        with(asset as Currency) {
может быть краш

2024-07-15 09:14 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/rv/AssetsAdapter.kt
> +class AssetsAdapter(
можно использовать ListAdapter

2024-07-15 09:15 UTC, Valentin2508247 commented
слишком много файлов в пулл реквесте

2024-07-16 21:17 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/domain/models/Asset.kt
> +data class Currency(
Не вижу как это применить к Currency, но Asset отлично вышел через sealed.

2024-07-16 21:22 UTC, ZenTaKr0fTeR111 commented
> слишком много файлов в пулл реквесте

Согласен, тут линтер с рефакторингом влез и доменный слой с тестовой датой наверное можно было отдельно сделать. Буду подобного избегать по мере возможностей.

2024-07-16 21:42 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/myportfolio/MainActivity.kt
> +                onBackPressedDispatcher.onBackPressed()
опиши плиз, в чём логика этих строк

2024-07-16 21:43 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/myportfolio/domain/models/Asset.kt
> +    val priceInSubunits: Int,
Что такое subunit?

2024-07-16 21:44 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/myportfolio/domain/models/Asset.kt
> +    fun getBasePrice() = priceInSubunits / 100.0
И линтер пропускает magic number?

2024-07-16 21:45 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/AssetListViewModel.kt
> +        get() = _baseCurrency
В чём плюс разделения одного uiState на разные лайвдаты

2024-07-16 22:08 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/MainActivity.kt
> +                onBackPressedDispatcher.onBackPressed()
Когда нажимается стрелка назад в app bar приложения, мы вызываем диспетчер и у него функцию, которая по деффолту вызывается при нажатии back button. Эта функция вызывает последний зарегистрированный коллбэк (который в данном случае я добавляю во фрагменте) по принципу стека.

2024-07-16 22:11 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/domain/models/Asset.kt
> +    val priceInSubunits: Int,
Центы, пенни, копейки и т.д.

![brave_ZIqqfaTn5k](https://github.com/user-attachments/assets/041a63a2-5529-4cf4-8d85-28c585b43462)

2024-07-16 22:14 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/domain/models/Asset.kt
> +    fun getBasePrice() = priceInSubunits / 100.0
Нет, я в исключения кинул😁

2024-07-16 22:21 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/AssetListViewModel.kt
> +        get() = _baseCurrency
Одно - это список активов, другое - валюта, которую мы меняем в настройках и отображаем. Я делал это просто для отображения на экране, пока не продумывал как это будет лежать в настройках и получаться.
А если ты про backing property, для инкапсуляции данных. Одна приватная для изменения, вторая публичная для чтения, чтобы абы кто не менял нам данные.

2024-07-17 08:12 UTC, Valentin2508247 requested changes

2024-07-17 08:12 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/rv/AssetViewHolder.kt
> +    abstract fun bind(asset: T, onItemClicked: (Int) -> Unit, viewModel: AssetListViewModel)
плохая идея передавать вьюмодель во вьюхолдер
один из вариантов - сделать отдельные UI модели

2024-07-17 08:12 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/rv/AssetViewHolder.kt
> +        binding.nameText.text = asset.name
можно красиво сделать через binding.apply

2024-07-17 08:12 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/rv/AssetViewHolder.kt
> +        itemView.setOnClickListener { onItemClicked(asset.id) }
логичнее itemView.setOnClickListener перенести в конец метода
отдельно настраивать текст, отдельно добавлять listeners

2024-07-17 08:12 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/rv/AssetViewHolder.kt
> +            asset.getBasePrice(),
тут не страшно, но обычно стоит избегать вычислений в методе bind

2024-07-17 08:12 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/rv/AssetViewHolder.kt
> +class BondViewHolder(private val binding: AssetBondItemBinding) : AssetViewHolder<Bond>(binding) {
аналогично

2024-07-17 08:12 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/rv/AssetViewHolder.kt
> +class CurrencyViewHolder(private val binding: AssetListItemBinding) :
аналогично

2024-07-22 14:18 UTC, Valentin2508247 requested changes

2024-07-22 14:18 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/rv/AssetsAdapter.kt
> +class AssetsAdapter(
нужно полностью убрать viewModel из адаптера

2024-07-22 14:18 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/rv/AssetsAdapter.kt
> +                AssetVHModel(asset, viewModel.baseCurrency),
плохо для производительности
будет создаваться много объектов при быстром скролле

2024-07-24 09:20 UTC, Valentin2508247 approved these changes

2024-07-26 16:12 UTC, merged