Feature/porfolio
ZenTaKr0fTeR111/MyPortfolio pull request #5
Opened 2024-07-19 10:46 UTC by DanilaKovaliou

добавлен viewHolder
добавлен Adapter

2024-07-29 21:35 UTC, ZenTaKr0fTeR111 requested changes
Где вью модель?
Где модель портфеля?
Хочется видеть нормальные именования, следование конвенциям и здравому смыслу

2024-07-29 21:35 UTC, ZenTaKr0fTeR111 commented on .gitignore
> +/scripts/pre-commit
Линтер не нужно игнорить, он часть проекта

2024-07-29 21:35 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/adapter/PortfolioAdapter.kt
> +class PortfolioAdapter : RecyclerView.Adapter<PortfolioViewHolder>() {
ListAdapter

2024-07-29 21:35 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/ui/portfolio_screen/DetailedPortfolioFragment.kt
> +    override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
Даже не знаю, как ты хочешь сделать экран детальной информации о портфеле через диалог, но ладно, посмотрим

2024-07-29 21:35 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/ui/portfolio_screen/PortfolioFragment.kt
> +    private val binding
Зачем нам 2 приватных биндинга?

2024-07-29 21:35 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/ui/portfolio_screen/PortfolioFragment.kt
> +            viewPortfolio.apply {
Ужас какой, давай так не делать

2024-07-29 21:35 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/ui/portfolio_screen/PortfolioFragment.kt
> +        portfolioAdapter.differ.submitList(assetsStorage)
Такого объекта нет, должно ошибку кинуть

2024-07-29 21:35 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/ui/portfolio_screen/PortfolioFragment.kt
> +//                )--помогите,пожалуйста ,что мне здесь надо исправить?????(мб AssetId)
Даже не знаю что сказать... Ты уверен, что экран детальной информации портфеля должен получать id актива?

2024-07-29 21:35 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/viewHolder/PortfolioViewHolder.kt
> +    fun setData(item: Asset, onClick: (Asset) -> Unit) {
Давай для порядка bind

2024-07-29 21:35 UTC, ZenTaKr0fTeR111 commented on app/src/main/res/layout/fragment_portfolio.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
Constraint внутри constraint? Прощайте, оптимизация и user experience

2024-07-29 21:35 UTC, ZenTaKr0fTeR111 commented on app/src/main/res/layout/fragment_portfolio.xml
> +        android:id="@+id/constraintLayout2"
Понятные имена хотелось бы

2024-07-29 21:35 UTC, ZenTaKr0fTeR111 commented on app/src/main/res/layout/fragment_portfolio.xml
> +        <androidx.constraintlayout.widget.ConstraintLayout
Constraint внутри constraint внутри constraint? От такого кода хочется застрелиться

2024-07-29 21:35 UTC, ZenTaKr0fTeR111 commented on app/src/main/res/layout/fragment_portfolio.xml
> +    <ScrollView
Зачем тебе скролл вью когда есть recycler?

2024-07-29 21:35 UTC, ZenTaKr0fTeR111 commented on app/src/main/res/layout/viewholer_portfolio.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Здесь нужно без констрейнта, много этих вьюх будет спавнится на экране при скролле, и уже мертвая оптимизация умрет в квадрате, если не в кубе

2024-07-29 21:35 UTC, ZenTaKr0fTeR111 commented on app/src/main/res/navigation/nav_graph.xml
> +        tools:layout="@layout/fragment_detailed_portfolio" />
Аргумент?

2024-07-29 21:35 UTC, ZenTaKr0fTeR111 commented on app/src/main/res/values/strings.xml
> +    <!-- TODO: Remove or change this placeholder text -->
Это нам явно без надобности

2024-07-30 12:20 UTC, Valentin2508247 requested changes

2024-07-30 12:20 UTC, Valentin2508247 commented on app/src/main/res/layout/viewholer_portfolio.xml
viewholer?

2024-07-30 12:20 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/adapter/PortfolioAdapter.kt
> +class PortfolioAdapter : RecyclerView.Adapter<PortfolioViewHolder>() {
давай использовать ListAdapter

2024-07-30 12:20 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/portfolio_screen/DetailedPortfolioFragment.kt
> +            // Установка высоты bottom sheet (можно задать высоту в пикселях или WRAP_CONTENT)
зачем коммент и пустой apply?

2024-07-30 12:20 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/viewHolder/PortfolioViewHolder.kt
> +//            imageView.setImageResource(item.imageRes)
ненужный код

2024-07-30 12:20 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/viewHolder/PortfolioViewHolder.kt
> +    fun setData(item: Asset, onClick: (Asset) -> Unit) {
обычно функцию называют bind или onBind

2024-07-30 12:20 UTC, Valentin2508247 commented on app/src/main/res/layout/fragment_portfolio.xml
упрости иерархию View, скорее всего хватит одного ConstraintLayout
не нужно оборачивать recyclerview в scroll

2024-08-30 13:44 UTC, closed without merging