settings layout and store
ZenTaKr0fTeR111/MyPortfolio pull request #6
Opened 2024-07-31 00:38 UTC by ZenTaKr0fTeR111

2024-07-31 09:14 UTC, Valentin2508247 requested changes

2024-07-31 09:14 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/AssetListFragment.kt
> +        val assets = MediatorLiveData<List<UIAsset>>().apply {
предоставляй из viewModel сразу LiveData<List<UIAsset>>
на уровне фрагмента только observe

2024-07-31 09:14 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/data/repository/PreferencesDataStoreRepository.kt
> +class PreferencesDataStoreRepository @Inject constructor(
нет обработки ошибок
обращения к preference могут вызывать краши

2024-07-31 09:14 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/data/repository/PreferencesDataStoreRepository.kt
> +            prefs[stringPreferencesKey(SETTINGS_CURRENCY_KEY)] ?: CurrencyCode.USD.name
можно создать закешированные preferenceKey один раз
stringPreferencesKey(SETTINGS_CURRENCY_KEY) будет при каждом обращении создавать новый объект

2024-08-01 13:08 UTC, Valentin2508247 requested changes

2024-08-01 13:08 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/AssetListFragment.kt
> +        activityViewModel.defaultCurrency.observe(viewLifecycleOwner) {
как будто ненужный observe
давай сделаем через MediatorLiveData на уровне viewModel

2024-08-02 12:11 UTC, Valentin2508247 approved these changes
гуд
лучше не делай force push
если есть вопросы с гитом - можешь писать

2024-08-02 15:14 UTC, ZenTaKr0fTeR111 commented
> гуд лучше не делай force push если есть вопросы с гитом - можешь писать

Да, я понимаю, что когда я перезаписываю коммит и кто-то сохранит себе старый коммит локально, и может даже начнет от него отводить собственные коммиты, то потом возникнут проблемы при синхронизации. В данном случае проблем быть не должно, никто больше ветку не трогает, пока она на ревью. Просто не хочется логи загромождать кучей коммитов, в которых исправлено пара строчек, поэтому я делаю amend.

2024-08-06 18:35 UTC, merged