detail screens for assets
ZenTaKr0fTeR111/MyPortfolio pull request #7
Opened 2024-08-06 22:19 UTC by ZenTaKr0fTeR111

2024-08-07 10:13 UTC, Valentin2508247 requested changes

2024-08-07 10:13 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/detailed_screen/DetailedAssetViewModel.kt
> +    private var _asset = MutableLiveData<Asset>()
private val

2024-08-07 10:13 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/detailed_screen/DetailedAssetViewModel.kt
> +    private var _conversionRates = MutableLiveData<List<Entry>>()
private val

2024-08-07 10:13 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/data/datasource/ConversionRateDataSource.kt
> +interface ConversionRateDataSource {
не очень хорошо расширяемый код
можно сделать один метод и подумать как задавать требуемые дни
fun getConversionRates(from: Currency, to: Currency, days: Int): List<ConversionRate>

2024-08-07 10:13 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/data/repository/ConversionRateRepositoryImpl.kt
> +            CurrencyCode.USD -> dataSource.getRatesUSD()
код допускает получение ConversionRate только в BYN валюту
лучше допускать возможность расширения: getConversionRate(from: CurrencyCode, to: CurrencyCode)

2024-08-07 10:13 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/domain/interactors/ConversionInteractor.kt
> +            }.take(span)
запрашивай ограниченное число данных из репозитория, а не все данные сразу

2024-08-07 10:13 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/domain/interactors/ConversionInteractor.kt
> +    private suspend fun invokeFetchFromRepository(
как будто можно написать проще

2024-08-07 10:13 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/detailed_screen/DateFormatter.kt
> +            .format(DateTimeFormatter.ofPattern("dd MMM"))
вынеси pattern в private val

2024-08-07 10:13 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/detailed_screen/DetailedAssetViewModel.kt
> +            val rates = arrayListOf<Entry>()
у list есть функция map
сделай отдельный класс mapper
у viewModelScope Dispatcher.Main.immediate
нельзя делать тяжелые операции (сортировку и маппинг) на UI потоке

2024-08-07 10:13 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/detailed_screen/DetailedBondItemFragment.kt
> +            issueDateValue.text = bond.dateOfIssuance
возможны краши при форматировании
сделай отдельный DateTimeUtils с методами для форматирования и обработкой ошибок

2024-08-07 10:13 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/detailed_screen/DetailedCurrencyItemFragment.kt
> +            conversionRateChart.apply {
в onViewCreated
 ```
conversionRateChart.apply {
    xAxis.position = XAxis.XAxisPosition.BOTTOM
    legend.isEnabled = false
}
```

2024-08-07 10:13 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/detailed_screen/DetailedCurrencyItemFragment.kt
> +            viewModel.conversionRates.observe(viewLifecycleOwner) { newConversionRates ->
observe в onViewCreated
сделай проверку на null, чтобы лишний раз много кода не вызывать

2024-08-08 00:19 UTC, pzinkevich42innowise requested changes

2024-08-08 00:19 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/myportfolio/Utils.kt
> +object DateTimeUtils : ValueFormatter() {
Экстеншены, не?

2024-08-08 00:19 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/detailed_screen/DetailedAssetViewModel.kt
> +        suspend fun mapConversionRatesToEntries(rates: List<ConversionRate>): List<Entry> {
Экстеншен, не?

2024-08-08 00:19 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/detailed_screen/DetailedAssetViewModel.kt
> +        get() = _conversionRates
Я бы объединил как-нибудь в одну большую модель

2024-08-08 08:10 UTC, Valentin2508247 requested changes

2024-08-08 08:10 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/domain/interactors/ConversionInteractor.kt
> +    enum class Period {
можно так
enum class Period(val days: Int) {
        WEEK(7),
        MONTH(31),
        YEAR(365)
}

2024-08-08 08:10 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/data/datasource/ConversionRateSampleSource.kt
> +        val days = when (period) {
val days = period.days

2024-08-08 08:10 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/detailed_screen/DetailedAssetViewModel.kt
> +            return withContext(Dispatchers.Default) {
я бы делал withContext(Dispatchers.Default) не в маппере
лучше, если маппер имеет только одну ответственность: трасформировать одну модель в другую

2024-08-14 08:02 UTC, Valentin2508247 approved these changes

2024-08-14 15:00 UTC, pzinkevich42innowise approved these changes
В целом ок, но в идеале можно поправить форматирование

2024-08-14 15:00 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/detailed_screen/DetailedCurrencyItemFragment.kt
> +            }
val period = when(id){ R.id... -> Period... }
viewModel.changePeriod(period)

2024-08-14 15:00 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/detailed_screen/DetailedCurrencyItemFragment.kt
> +            }
Аналогично
val chip = when(...) { Period... -> rates...Chip }
chip.isChecked = true
И про else не забудь

Также можно на ChipGroup посмотреть и через неё выделять

2024-08-14 17:38 UTC, merged