loading conversion rates from api and saving to db
ZenTaKr0fTeR111/MyPortfolio pull request #9
Opened 2024-08-19 23:20 UTC by ZenTaKr0fTeR111

2024-08-20 14:08 UTC, Valentin2508247 requested changes

2024-08-20 14:08 UTC, Valentin2508247 commented on app/build.gradle.kts
> +    implementation(platform(libs.okhttp.bom))
нужны ли okHttp зависимости?

2024-08-20 14:08 UTC, Valentin2508247 commented on gradle/libs.versions.toml
> +okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttpBom" }
нужны ли okHttp зависимости?

2024-08-20 14:08 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/Utils.kt
> +const val CONVERSION_API_BASE_URL = "https://api.nbrb.by/"
Utils - не место для констант конфигурации api

2024-08-20 14:08 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/data/datasource/conversion_rate/remote/ConversionRateApiDataSource.kt
> +        return withContext(Dispatchers.Default) {
не обязательно переключать на Dispatchers.Default
у тебя нет особо тяжелых операций в map
переключение между потоками тоже занимает ресурсы

2024-08-20 14:08 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/domain/models/CurrencyCode.kt
> +        }
неэффективно, тут сложность O(n*m), где n - размер списка с api, m - число типов в enum
можно сделать O(n)
для каждого элемента из списка с api выполняется проход по элементам enum

2024-08-20 14:08 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/AssetListFragment.kt
>              adapter.submitList(it)
if (it == null) return

2024-08-20 14:08 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/ui/assets_screen/AssetListFragment.kt
такой код может привести к багам с прогрессбаром в дальнейшем
у LiveData default value null, прогрессбар может спрятаться когда не должен

2024-08-20 14:08 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/Utils.kt
> +fun LocalDate.formatAppDetails(formatSubject: FormatSubject): String {
непонятный нейминг formatAppDetails
содержит доп логику
метод каждый раз создает новые объекты форматтера

2024-08-20 14:08 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/Utils.kt
> +fun LocalDate.formatAppDetails(formatSubject: FormatSubject): String {
я бы сделал так:

```
object Formatters {
    val BOND_DETAILS_FORMATTER by lazy { DateTimeFormatter.ofPattern("MMMM d, yyyy")} // July 15, 2021
    val API_ARGS_FORMATTER by lazy { DateTimeFormatter.ofPattern("yyyy-MM-dd")  } // 2021-07-15
}

fun LocalDate.safeFormat(formatter: DateTimeFormatter): String {
    return try {
        format(formatter)
    } catch (e: DateTimeException) {
        println(
            "Indicated problems with creating, querying or manipulating date-time object $this."
        )
        e.printStackTrace()
        return this.toString()
    }
}
```

2024-08-20 14:08 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/Utils.kt
> +        LocalDate.parse(this.split("T")[0])
точно ли split нужен?
как-будто можно по-другому

2024-08-20 14:08 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/data/datasource/conversion_rate/local/ConversionRateDbSource.kt
> +                conversionRateDao.getRatesForCurrency(CurrencyCode.USD, days)
почему только в CurrencyCode.USD?

2024-08-20 14:08 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/data/datasource/conversion_rate/local/ConversionRateDbSource.kt
> +                if (isByn) CurrencyCode.BYN else conversionRateEntity.sourceCurrency,
очень странные проверки
можно ли обойтись без проверок?

2024-08-20 14:08 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/data/datasource/conversion_rate/local/ConversionRateDbSource.kt
> +        val dbRates = withContext(Dispatchers.Default) {
можно все делать сразу на IO, не обязательно переключаться
переключение потоков тоже занимает ресурсы

2024-08-20 14:08 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/data/repository/ConversionRateRepositoryImpl.kt
>  class ConversionRateRepositoryImpl @Inject constructor(
я бы переключал Dispatchers в репозитории, а не в data source

2024-08-20 14:08 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/data/repository/ConversionRateRepositoryImpl.kt
> +        val sourceCurrencyRates = getRatesForCurrency(sourceCurrency, days)
у тебя загрузка данных не параллельна
сделай загрузку параллельной
можешь воспользоваться async {getRatesForCurrency(sourceCurrency, days)}

2024-08-20 14:08 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/di/AppModule.kt
> +            )
зависимости можно через DI передавать, а не вручную создавать

2024-08-20 14:08 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/di/AppModule.kt
> +            .addConverterFactory(Json.asConverterFactory("application/json".toMediaType()))
аналогично с converterFactory

2024-08-21 16:51 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/myportfolio/data/datasource/conversion_rate/local/ConversionRateDbSource.kt
> +                if (isByn) CurrencyCode.BYN else conversionRateEntity.sourceCurrency,
Вряд ли. Мы получаем с апи и сохраняем курс в бд по отношению к рублю, курс рубля к рублю мы не получем. Можно запариться и как-то сохранять такой курс вручную, но тогда бд будет полна записей BYN 1.0 на каждый день, что кажется куда хуже. Может есть способ которого я не вижу, есть идеи?

2024-08-22 12:04 UTC, Valentin2508247 requested changes

2024-08-22 12:04 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/Config.kt
может, лучше перенести в data слой?

2024-08-22 12:04 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/data/db/conversion_rates/ConversionRateDao.kt
> +    @Query(
сделай все функции в DAO suspend

2024-08-22 12:04 UTC, Valentin2508247 commented on app/src/main/java/com/example/myportfolio/data/datasource/conversion_rate/local/ConversionRateDbSource.kt
> +    override fun getRatesForCurrency(
сделай getRatesForCurrency и saveRates suspend

2024-08-22 17:26 UTC, Valentin2508247 approved these changes

2024-08-23 00:30 UTC, merged